async function getNumberOfProducts(conn) {
  try {

  } catch (err) {
    console.log(err);
  }
}